sudo: false

language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps

script:
  - make all
